force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Profile_Image__c.field-meta.xml
<CustomField>
    <fullName>Profile_Image__c</fullName>
    <label>Profile Image</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Apex Classes/ImageSelector.cls
public with sharing class ImageSelector {


  public static ContentVersion getCVRecord(string cvId){
   
  ContentVersion file = [Select Id, Title, ContentDocumentId from ContentVersion where Id = : cvId];
  return file;
  }

  public static ContentDistribution getCDRecord(string cdId){
    ContentDistribution cd = [SELECT DistributionPublicUrl, ContentDownloadUrl FROM ContentDistribution WHERE Id = :cdId LIMIT 1];
    return cd;
  }

   
  public static list<Employee__c> getImageLink(string employeeId, string publicLink ){

   list<Employee__c> getEmployeeDetails = [Select Id, Profile_Image__c from Employee__c Where Id = :employeeId];
   getEmployeeDetails[0].Profile_Image__c = publicLink;

   update getEmployeeDetails;
   return getEmployeeDetails;

  }

}