force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Amount_To_Be_Refund__c.field-meta.xml
<CustomField>
    <fullName>Amount_To_Be_Refund__c</fullName>
    <label>Amount To Be Refund</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Speakers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <label>Speaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Ticket_Amount__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Amount__c</fullName>
    <label>Ticket Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Apex Classes/SpeakerTriggerHandler.cls
public with sharing class SpeakerTriggerHandler extends TriggerHandler {
    
    private List<Speaker__c> triggerNew;
    private Map<Id, Speaker__c> triggerOldMap;

    public override void beforeUpdate() {
        triggerOldMap = (Map<Id, Speaker__c>)Trigger.oldMap;
        triggerNew = (List<Speaker__c>)Trigger.new;

        Set<String> speakerNames = new Set<String>();
        Set<String> speakerEmails = new Set<String>();

        for (Speaker__c newSpeaker : triggerNew) {
            Speaker__c oldSpeaker = triggerOldMap.get(newSpeaker.Id);
            
            // Handling Approved Speakers
            if (newSpeaker.Approval_Status__c == 'Approved' && oldSpeaker.Approval_Status__c != 'Approved') {
                speakerNames.add(newSpeaker.Speaker_Name__c);
                speakerEmails.add(newSpeaker.Email__c);
            }
            
            // Handling Rejected Speakers
            if (newSpeaker.Approval_Status__c == 'Rejected' && oldSpeaker.Approval_Status__c != 'Rejected') {
                // handleRejectedSpeaker(newSpeaker, oldSpeaker);
                  speakerNames.add(newSpeaker.Speaker_Name__c);
                speakerEmails.add(newSpeaker.Email__c);
            }
        }

        if (!speakerNames.isEmpty() && !speakerEmails.isEmpty()) {
            Map<String, Id> attendeeMap = AttendeeSelector.getAttendeesbyNameandEmail(speakerNames, speakerEmails);

            Set<Id> attendeeIds = new Set<Id>(attendeeMap.values());
            Map<Id, Decimal> ticketAmountMap = TicketSelector.getTicketAmounts(attendeeIds);

            for (Speaker__c speaker : triggerNew) {
                String attendeeKey = speaker.Speaker_Name__c + '|' + speaker.Email__c;
                if (attendeeMap.containsKey(attendeeKey) && attendeeIds.contains(attendeeMap.get(attendeeKey))) {
                    speaker.Attendee__c = attendeeMap.get(attendeeKey);
                    System.debug('speaker attendee ' + speaker.Attendee__c);
                    speaker.Ticket_Amount__c = ticketAmountMap.get(attendeeMap.get(attendeeKey));

                    if(speaker.Approval_Status__c=='Approved'){
                         speaker.Amount_To_Be_Refund__c = speaker.Ticket_Amount__c;
                         speaker.Refund_Amount__c = speaker.Ticket_Amount__c;

                    }
                   if (speaker.Approval_Status__c == 'Rejected') {
                                Decimal discountAmount = speaker.Ticket_Amount__c * 0.20;
                           speaker.Amount_To_Be_Refund__c = discountAmount;
                         speaker.Refund_Amount__c =discountAmount;
                   }
                
                }
            }
        }
    }

  

    public SpeakerTriggerHandler() {
        this.triggerNew = (List<Speaker__c>)Trigger.new;
    }
}