force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Amount_To_Be_Refund__c.field-meta.xml
<CustomField>
    <fullName>Amount_To_Be_Refund__c</fullName>
    <label>Amount To Be Refund</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Speakers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <label>Speaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Ticket_Amount__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Amount__c</fullName>
    <label>Ticket Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <label>Voucher Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Apex Classes/SpeakerSelector.cls
/**
 *@author: Fatima
* @description: For retrieving Speaker records
* @since: 07/05/24
 */

public without sharing class SpeakerSelector {
    

/**
 * @description retrieving speaker record
 * @param whereClause 
 * @return  `List<Speaker__c>`
 */
    public static List<Speaker__c> getSpeaker(String whereClause) {
        String clause = whereClause != null ? ' WHERE ' + whereClause : '';
        String query = 'SELECT Id,Attendee__c, Ticket_Amount__c,Amount_To_Be_Refund__c FROM Speaker__c ' + clause;
        return Database.query(query);
    }

    /**
     * @description Retrieving speaker by Id
     * @param Id 
     * @return  `Speaker__c`
     */
    public Speaker__c getSpeakerById(String Id) {

        String clause =  ' Id = \'' + Id + '\'';
        List<Speaker__c> speaker = getSpeaker(clause);
        if (speaker.size() > 0) {
             return speaker.get(0);
        }
        return null;
    
      
    }
    public static List<Speaker__c> getlstofSpeakerID(String whereClause) {
        String comingWhereClause = ' Id = \'' + whereClause + '\'';
        String clause = comingWhereClause != null ? ' WHERE' + comingWhereClause : '';
        System.debug('@@ clause::'+clause);
        String query = 'SELECT Id,Speaker_name__c,Approval_Status__c,Voucher_code__c FROM Speaker__c ';
        query = query +clause;
        system.debug('Check Query' +query);
        return Database.query(query);
    }
}