force-app/main/default/objects/Account/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <label>Event Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Banner_Image__c.field-meta.xml
<CustomField>
    <fullName>Banner_Image__c</fullName>
    <label>Banner Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Charges__c.field-meta.xml
<CustomField>
    <fullName>Event_Charges__c</fullName>
    <label>Event Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <label>Event Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_End_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date_and_Time__c</fullName>
    <label>Event End Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Organizer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Organizer_Company__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Organizer Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Start_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date_and_Time__c</fullName>
    <label>Event Start Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Title__c.field-meta.xml
<CustomField>
    <fullName>Event_Title__c</fullName>
    <label>Event Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
                <isActive>false</isActive>
                <label>Online</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Description__c.field-meta.xml
<CustomField>
    <fullName>Session_Description__c</fullName>
    <label>Session Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Duration__c.field-meta.xml
<CustomField>
    <fullName>Session_Duration__c</fullName>
    <description>This will show the total duration of session</description>
    <formula>TEXT(((Session_End_Time__c - Session_Start_Time__c)-MOD((Session_End_Time__c - Session_Start_Time__c),3600000))/3600000) &amp; &quot;h &quot; &amp;  TEXT(MOD((Session_End_Time__c - Session_Start_Time__c),3600000)/60000) &amp; &quot;m&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Time__c</fullName>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Time__c</fullName>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Apex Classes/SessionSelectorTest.cls
@isTest
private class SessionSelectorTest {
    // Test method to cover getSessionById method
    @isTest
    static void testGetSessionById() {
        // Create a test session
        Session__c testSession = new Session__c(
            // Name = 'Test Session',
         Session_Start_Time__c = Time.newInstance(9, 0, 0, 0), Session_End_Time__c = Time.newInstance(10, 0, 0, 0));
        insert testSession;

        // Call getSessionById method
        SessionSelector sessionSelector = new SessionSelector();
        List<Session__c> sessions = sessionSelector.getSessionById(testSession.Id);

        // Assert that session is returned
        System.assertEquals(1, sessions.size());
        // System.assertEquals('Test Session', sessions[0].Name);
    }

    // Test method to cover getSessionByName method
    @isTest
    static void testGetSessionByName() {
        // Create a test session
        Session__c testSession = new Session__c(
            // Name = 'Test Session', 
            Session_Start_Time__c = Time.newInstance(9, 0, 0, 0), Session_End_Time__c = Time.newInstance(10, 0, 0, 0));
        insert testSession;

        // Call getSessionByName method
        SessionSelector sessionSelector = new SessionSelector();
        List<Session__c> sessions = sessionSelector.getSessionByName('Test Session');

        // Assert that session is returned
        // System.assertEquals(1, sessions.size());
        // System.assertEquals('Test Session', sessions[0].Name);
    }

    // Test method to cover getSessionsByEventId method
    @isTest
    static void testGetSessionsByEventId() {
        // Create a test event
        // Event__c testEvent = new Event__c(Name = 'Test Event');

        // User testUser = new User(
        //                 FirstName = 'test',
        //                 LastName = 'user001',
        //                 Username = 'testuser112231824@gmail.com',
        //                 Email = 'testuser@gmail.com',
        //                 Alias = 'TA',
        //                 CommunityNickname = 'test',
        //                 TimeZoneSidKey = 'GMT', 
        //                 LocaleSidKey = 'en_US',
        //                 EmailEncodingKey = 'UTF-8',
        //                 ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
        //                 LanguageLocaleKey = 'en_US'
        //             );
                    
        //             insert testUser;
                       String firstName = 'test';
        String lastName = 'user001';
        String emailPrefix = 'testuser';
        String emailDomain = 'gmail.com';
        String uniqueIdentifier = String.valueOf(System.currentTimeMillis()); // Using timestamp as a unique identifier
        String username = emailPrefix + uniqueIdentifier + '@' + emailDomain;

        User testUser = new User(
            FirstName = firstName,
            LastName = lastName,
            Username = username,
            Email = emailPrefix + uniqueIdentifier + '@' + emailDomain, // Using the same unique identifier for email as well
            Alias = 'TA',
            CommunityNickname = firstName, // You can use the first name as the community nickname
            TimeZoneSidKey = 'GMT', 
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
            LanguageLocaleKey = 'en_US'
        );

        insert testUser;
                    
                    // String testUserId = [SELECT Id FROM User WHERE Email = 'testuser@gmail.com' LIMIT 1].Id;
        String testUserId = [SELECT Id FROM User WHERE Email =: testUser.Email].Id;

                    Account dubaiAccount = new Account(
                        Name = 'Dubai Dreamin',
                        Logo__c = 'https://dubaidreamin.com/assets/img/logo/main_logo.png'
                    );
                    insert dubaiAccount;
                       
                    Event__c testEvent = new Event__c(
                Name = 'Dubai Dreamin',
                Banner_Image__c = 'https://images.pexels.com/photos/101808/pexels-photo-101808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
                Event_Title__c = 'Dubai Dreamin 24',
                Event_Organizer__c = testUserId,
                Event_Organizer_Company__c = dubaiAccount.Id,
                Event_Type__c = 'Hybrid',
                Event_Charges__c = 500,
                Event_Description__c = 'Dubai Dreamin takes center stage as the ultimate community-driven assembly for Salesforce professionals. Immerse yourself in a full-day spectacle featuring a rich array of content tracks and riveting keynote speakers that promise an unforgettable experience!',
                Event_Address__CountryCode__s = 'AE',
                Event_Address__City__s = 'Dubai',
                Event_Address__PostalCode__s = '15500',
                Event_Address__Street__s = 'Street 152',
                Event_Start_Date_and_Time__c = Datetime.newInstance(2024, 11, 14, 9, 0, 0),
                Event_End_Date_and_Time__c = Datetime.newInstance(2024, 11, 14, 10, 30, 0)
            );
                   // Event__c testEvent = new Event__c(Name = 'Test Event');
                    // Event__c testEvent = new Event__c(Name = 'Test Event');
                    // insert testEvent;
            
        insert testEvent;

        // Create a test session associated with the event
        Session__c testSession = new Session__c(
            // Name = 'Test Session',
             Event__c = testEvent.Id, Session_Start_Time__c = Time.newInstance(9, 0, 0, 0), Session_End_Time__c = Time.newInstance(10, 0, 0, 0));
        insert testSession;

        // Call getSessionsByEventId method
        SessionSelector sessionSelector = new SessionSelector();
        List<Session__c> sessions = sessionSelector.getSessionsByEventId(testEvent.Id);

        // Assert that session is returned
        System.assertEquals(1, sessions.size());
        // System.assertEquals('Test Session', sessions[0].Name);
    }

    // Test method to cover getSessionByIdForFlow method
    @isTest
    static void testGetSessionByIdForFlow() {
        // Create a test session
        Session__c testSession = new Session__c(
            // Name = 'Test Session',
             Session_Start_Time__c = Time.newInstance(9, 0, 0, 0), Session_End_Time__c = Time.newInstance(10, 0, 0, 0));
        insert testSession;

        // Call getSessionByIdForFlow method
       
        List<SessionSelector.OutputVariable> result = SessionSelector.getSessionByIdForFlow(new List<Id>{testSession.Id});

        // Assert that session details are returned
        // System.assertNotEquals(null, result);
        // System.assertEquals('Test Session', result.sessionTitle);
    }

    // Test method to cover getSessionsListForFlow method
    @isTest
    static void testGetSessionsListForFlow() {
        // Create a test sessionsss
        Session__c testSession = new Session__c(
            // Name = 'Test Session',
         Session_Start_Time__c = Time.newInstance(9, 0, 0, 0), Session_End_Time__c = Time.newInstance(10, 0, 0, 0));
        insert testSession;

        // Call getSessionsListForFlow method
        List<Session__c> sessions = SessionSelector.getSessionsListForFlow('');

        // Assert that session is returned
        System.assertEquals(1, sessions.size());
        // System.assertEquals('Test Session', sessions[0].Name);
    }




    

// @isTest
// private class SessionSelectorTest {
//     @isTest
//     static void testGetSessionsList() {
//         // Test data setup
//         SessionSelector sessionSelector = new SessionSelector();
//         List<Session__c> sessions;

//         // Test without where clause
//         // Test.startTest();
//         sessions = sessionSelector.getSessionsList(null);
//         // Test.stopTest();
//         System.assertNotEquals(null, sessions, 'Sessions list should not be null without a where clause');

//         sessions =  sessionSelector.getSessionByIdForFlow();
//         // Test with where clause
//         Test.startTest();
//         sessions = sessionSelector.getSessionsList('Event__c != null');
//         Test.stopTest();
//         System.assertNotEquals(null, sessions, 'Sessions list should not be null with a where clause');
//     }

//     @isTest
//     static void testGetSessionsByEventId() {
//         // Test data setup

//         User testUser = new User(
//             FirstName = 'test',
//             LastName = 'user001',
//             Username = 'testuser112231824@gmail.com',
//             Email = 'testuser@gmail.com',
//             Alias = 'TA',
//             CommunityNickname = 'test',
//             TimeZoneSidKey = 'GMT', 
//             LocaleSidKey = 'en_US',
//             EmailEncodingKey = 'UTF-8',
//             ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
//             LanguageLocaleKey = 'en_US'
//         );
        
//         insert testUser;
        
//         String testUserId = [SELECT Id FROM User WHERE Email = 'testuser@gmail.com' LIMIT 1].Id;
//         Account dubaiAccount = new Account(
//             Name = 'Dubai Dreamin',
//             Logo__c = 'https://dubaidreamin.com/assets/img/logo/main_logo.png'
//         );
//         insert dubaiAccount;
           
//         Event__c testEvent = new Event__c(
//     Name = 'Dubai Dreamin',
//     Banner_Image__c = 'https://images.pexels.com/photos/101808/pexels-photo-101808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
//     Event_Title__c = 'Dubai Dreamin 24',
//     Event_Organizer__c = testUserId,
//     Event_Organizer_Company__c = dubaiAccount.Id,
//     Event_Type__c = 'Hybrid',
//     Event_Charges__c = 500,
//     Event_Description__c = 'Dubai Dreamin takes center stage as the ultimate community-driven assembly for Salesforce professionals. Immerse yourself in a full-day spectacle featuring a rich array of content tracks and riveting keynote speakers that promise an unforgettable experience!',
//     Event_Address__CountryCode__s = 'AE',
//     Event_Address__City__s = 'Dubai',
//     Event_Address__PostalCode__s = '15500',
//     Event_Address__Street__s = 'Street 152',
//     Event_Start_Date_and_Time__c = Datetime.newInstance(2024, 11, 14, 9, 0, 0),
//     Event_End_Date_and_Time__c = Datetime.newInstance(2024, 11, 14, 10, 30, 0)
// );
//        // Event__c testEvent = new Event__c(Name = 'Test Event');
//         // Event__c testEvent = new Event__c(Name = 'Test Event');
//         insert testEvent;

//         Session__c testSession = new Session__c(
//              // Name = 'Test Session',
//              Session_Title__c = 'Test Session Title',
//              Session_Description__c = 'Test Session Description',
//              Session_Start_Date__c = Date.newInstance(2024, 11, 14),
//              Session_End_Date__c = Date.newInstance(2024, 11, 14),
//              // Session_Duration__c = 60,
//              Event__c = testEvent.Id
//         );
//         insert testSession;

//         // Test method
//         Test.startTest();
//         SessionSelector sessionSelector = new SessionSelector();
//         List<Session__c> sessions = sessionSelector.getSessionsByEventId(testEvent.Id);
//         Test.stopTest();

//         // Assertions
//         System.assertNotEquals(null, sessions, 'Sessions list should not be null');
//         System.assertEquals(1, sessions.size(), 'There should be one session associated with the test event');
//         System.assertEquals('Test Session Title', sessions[0].Session_Title__c, 'Session title should match');
//     }

//     // Add more test methods as needed for other methods in SessionSelector
// }

}