force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Information__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Information__c</fullName>
    <label>Speaker Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <label>Speaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Social_Media__c</fullName>
    <label>Speaker Social Media</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Target__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Target__c</fullName>
    <label>Speaker Target</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admins</fullName>
            </value>
            <value>
                <fullName>Developers</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Marketing Technologists</fullName>
            </value>
            <value>
                <fullName>Executives</fullName>
            </value>
            <value>
                <fullName>End Users</fullName>
            </value>
            <value>
                <fullName>ISV/SI Partners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Apex Classes/SessionSpeakerSelectorTest.cls
@isTest
public class SessionSpeakerSelectorTest {
    @isTest
    static void testGetSessionSpeakerBySpeakerId(){


        Speaker__c testSpeaker = new Speaker__c(
            Speaker_Name__c = 'Test Speaker',
            Speaker_Social_Media__c = 'Test Social Media',
            Phone_Number__c = '1234567890',
            Speaker_Target__c = 'Admins',
            Email__c = 'test@example.com',
            Company_Name__c = 'Test Company',
            Speaker_Information__c = 'Test Information',
            Approval_Status__c = 'Pending'
        );
        insert testSpeaker;

        SessionSpeakerSelector testobje = new SessionSpeakerSelector();
        testobje.getSessionSpeakerBySpeakerId(testSpeaker.Id);
    }
}