force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Already_Presented_Link__c.field-meta.xml
<CustomField>
    <fullName>Already_Presented_Link__c</fullName>
    <label>Already Presented Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Does_session_already_presented__c.field-meta.xml
<CustomField>
    <fullName>Does_session_already_presented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Does session already presented?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Individual_Presenter_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Individual_Presenter_Confirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Individual Presenter Confirmation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Intellectual_Property_Rights_Compliance__c.field-meta.xml
<CustomField>
    <fullName>Intellectual_Property_Rights_Compliance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Intellectual Property Rights Compliance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Intro_Video_Link__c.field-meta.xml
<CustomField>
    <fullName>Intro_Video_Link__c</fullName>
    <label>Intro Video Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Description__c.field-meta.xml
<CustomField>
    <fullName>Session_Description__c</fullName>
    <label>Session Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Time__c</fullName>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Expertise_Details__c.field-meta.xml
<CustomField>
    <fullName>Session_Expertise_Details__c</fullName>
    <label>Session Expertise Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Time__c</fullName>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Track__c.field-meta.xml
<CustomField>
    <fullName>Session_Track__c</fullName>
    <label>Session Track</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Data Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Analytics Cloud</fullName>
            </value>
            <value>
                <fullName>Integration Cloud</fullName>
            </value>
            <value>
                <fullName>Manufacturing Cloud</fullName>
            </value>
            <value>
                <fullName>Financial Services Cloud</fullName>
            </value>
            <value>
                <fullName>Education Services Cloud</fullName>
            </value>
            <value>
                <fullName>Nonprofit Cloud</fullName>
            </value>
            <value>
                <fullName>Health Cloud</fullName>
            </value>
            <value>
                <fullName>Vaccine Cloud</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Experience Cloud1</fullName>
                <isActive>false</isActive>
                <label>Experience Cloud1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Why_Session_is_Chosen__c.field-meta.xml
<CustomField>
    <fullName>Why_Session_is_Chosen__c</fullName>
    <description>Please take a moment to tell us why you think we should select your
presentation.</description>
    <label>Why Session is Chosen?</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Speaker_Age__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Age__c</fullName>
    <label>Speaker Age</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Gender__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Gender__c</fullName>
    <label>Speaker Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Information__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Information__c</fullName>
    <label>Speaker Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <label>Speaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Role__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Role__c</fullName>
    <label>Speaker Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admins</fullName>
            </value>
            <value>
                <fullName>Developers</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Marketing Technologists</fullName>
            </value>
            <value>
                <fullName>Executives</fullName>
            </value>
            <value>
                <fullName>End Users</fullName>
            </value>
            <value>
                <fullName>ISV/SI Partners</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
                <isActive>false</isActive>
                <label>Architect</label>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
                <isActive>false</isActive>
                <label>Business Analyst</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <isActive>false</isActive>
                <label>CEO</label>
            </value>
            <value>
                <fullName>Designer</fullName>
                <isActive>false</isActive>
                <label>Designer</label>
            </value>
            <value>
                <fullName>Developer</fullName>
                <isActive>false</isActive>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Manager</fullName>
                <isActive>false</isActive>
                <label>Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Social_Media__c</fullName>
    <label>Speaker Social Media</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Target__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Target__c</fullName>
    <label>Speaker Target</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admins</fullName>
            </value>
            <value>
                <fullName>Developers</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Marketing Technologists</fullName>
            </value>
            <value>
                <fullName>Executives</fullName>
            </value>
            <value>
                <fullName>End Users</fullName>
            </value>
            <value>
                <fullName>ISV/SI Partners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Type__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Type__c</fullName>
    <label>Speaker Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Speaker</fullName>
            </value>
            <value>
                <fullName>Co-Speaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Apex Classes/ApprovalProcessController.cls
/**
 * 
 * @author Faraz
 * @since March 2024
 */
public class ApprovalProcessController { 
    @AuraEnabled(cacheable=true)
    public static List<DenormalizedSession> getSessionTime(String recordId){

        ApprovalProcessSelector approvalProcessInstance = new ApprovalProcessSelector();    
       
        List<ProcessInstanceWorkitem>  selectedProcessInstanceWorkItem =  approvalProcessInstance.getProcessInstanceWorkItemById(recordId);     
        List<ProcessInstance> selectedProcessInstance =  approvalProcessInstance.getProcessInstanceById(selectedProcessInstanceWorkItem[0].ProcessInstanceId);
             
          
    SessionSelector sessionSelectorInstance = new SessionSelector();
    List<Session__c> selectedSessions =  sessionSelectorInstance.getSessionById(selectedProcessInstance[0].TargetObjectId);

       SessionSpeakerSelector sessionSpeakerSelectorInstance = new SessionSpeakerSelector();
       List<Speaker__c> selectedSessionSpeaker =  sessionSpeakerSelectorInstance.getSpeakersBySessionId(selectedSessions[0].Id);

    List<DenormalizedSession> sessionItemsList = new List<DenormalizedSession>();

     

    
    DenormalizedSession denormalizedSession = new DenormalizedSession();
       denormalizedSession.setSessionName(selectedSessions[0].Name); 
       denormalizedSession.setSessionDescription(selectedSessions[0].Session_Description__c); 
       denormalizedSession.setSessionTrack(selectedSessions[0].Session_Track__c); 
       denormalizedSession.setSessionTitle(selectedSessions[0].Session_Title__c); 
       denormalizedSession.setStartTime(String.valueof(selectedSessions[0].Session_Start_Time__c));
       denormalizedSession.setEndTime(String.valueof(selectedSessions[0].Session_End_Time__c));
       denormalizedSession.setSessionSelectionDetails(selectedSessions[0].Why_Session_is_Chosen__c);
       denormalizedSession.setSessionExpertiseOnSubject(selectedSessions[0].Session_Expertise_Details__c);
       denormalizedSession.setSessionIntroLink(selectedSessions[0].Intro_Video_Link__c);
       denormalizedSession.setSessionLevel(selectedSessions[0].Level__c);
       denormalizedSession.setSessionPresentedLink(selectedSessions[0].Already_Presented_Link__c);
       denormalizedSession.setSessionAlreadyPresented(selectedSessions[0].Does_session_already_presented__c);
       denormalizedSession.setIPRCompliance(selectedSessions[0].Intellectual_Property_Rights_Compliance__c);
       denormalizedSession.setIndividualPresentor(selectedSessions[0].Individual_Presenter_Confirmation__c);
     
     
     
       for(Speaker__c selectedSpeaker:selectedSessionSpeaker){
        if(selectedSpeaker.Speaker_Type__c=='Primary Speaker'){
          denormalizedSession.setSpeakerName(selectedSpeaker.Speaker_Name__c); 
          denormalizedSession.setSpeakerSocialMedia(selectedSpeaker.Speaker_Social_Media__c); 
          denormalizedSession.setSpeakerPhone(selectedSpeaker.Phone_Number__c); 
          denormalizedSession.setSpeakerTarget(selectedSpeaker.Speaker_Target__c);
          denormalizedSession.setSpeakerRole(selectedSpeaker.Speaker_Role__c); 
          denormalizedSession.setSpeakerEmail(selectedSpeaker.Email__c); 
          denormalizedSession.setSpeakerCompanyName(selectedSpeaker.Company_Name__c); 
          denormalizedSession.setSpeakerInformation(selectedSpeaker.Speaker_Information__c); 
          denormalizedSession.setSpeakerAge(selectedSpeaker.Speaker_Age__c); 
          denormalizedSession.setSpeakerGender(selectedSpeaker.Speaker_Gender__c); 
   

        }
        if(selectedSpeaker.Speaker_Type__c=='Co-Speaker'){
          denormalizedSession.setCoSpeakerName(selectedSpeaker.Speaker_Name__c); 
          denormalizedSession.setCoSpeakerPhone(selectedSpeaker.Phone_Number__c); 
          denormalizedSession.setCoSpeakerRole(selectedSpeaker.Speaker_Role__c); 
          denormalizedSession.setCoSpeakerEmail(selectedSpeaker.Email__c); 
          denormalizedSession.setCoSpeakerCompanyName(selectedSpeaker.Company_Name__c); 
   

        }


       }
     
     
     
       sessionItemsList.add(denormalizedSession);
     
       return sessionItemsList;
    }


    @AuraEnabled
    public static void setSessionTime(String sessionName, String sessionStartTime, String sessionEndTime){
   
        Time startTime = Time.newInstance(Integer.valueOf(sessionStartTime.split(':')[0]), Integer.valueOf(sessionStartTime.split(':')[1]), 0 ,0);
        Time endTime  = Time.newInstance(Integer.valueOf(sessionEndTime.split(':')[0]), Integer.valueOf(sessionEndTime.split(':')[1]), 0 ,0);
 

        Date myDate = Date.newInstance(2024, 12, 9);
        Datetime startDateTime = Datetime.newInstance(myDate.year(), myDate.month(), myDate.day(), startTime.hour(), startTime.minute(), startTime.second());
        Datetime endDateTime = Datetime.newInstance(myDate.year(), myDate.month(), myDate.day(), endTime.hour(), endTime.minute(), endTime.second());
  

        Long timeAvailable = endDateTime.getTime() - startDateTime.getTime();
        timeAvailable /= 60000;
       
        if(timeAvailable<30 && timeAvailable>60){
          throw new CustomException('Time Difference must be 30-60 minutes');
        }

      SessionSelector selectedSessionByName = new SessionSelector();

      List<Session__c> sessionList = selectedSessionByName.getSessionByName(sessionName);
      sessionList[0].Session_Start_Time__c= Time.newInstance(Integer.valueOf(sessionStartTime.split(':')[0]), Integer.valueOf(sessionStartTime.split(':')[1]), 0 ,0);
      sessionList[0].Session_End_Time__c= Time.newInstance(Integer.valueOf(sessionEndTime.split(':')[0]), Integer.valueOf(sessionEndTime.split(':')[1]), 0 ,0);
  
    Database.update(sessionList, true);
     


    }

public class CustomException extends Exception {}

}