force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session_Description__c.field-meta.xml
<CustomField>
    <fullName>Session_Description__c</fullName>
    <label>Session Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Time__c</fullName>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Time__c</fullName>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Session Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speaker_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speaker_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <description>Speaker Name</description>
    <formula>Speaker__r.Speaker_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Speaker Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Age__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Age__c</fullName>
    <label>Speaker Age</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Gender__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Gender__c</fullName>
    <label>Speaker Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Information__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Information__c</fullName>
    <label>Speaker Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <label>Speaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Profile_Image__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Profile_Image__c</fullName>
    <label>Speaker Profile Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Role__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Role__c</fullName>
    <label>Speaker Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admins</fullName>
            </value>
            <value>
                <fullName>Developers</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Marketing Technologists</fullName>
            </value>
            <value>
                <fullName>Executives</fullName>
            </value>
            <value>
                <fullName>End Users</fullName>
            </value>
            <value>
                <fullName>ISV/SI Partners</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
                <isActive>false</isActive>
                <label>Architect</label>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
                <isActive>false</isActive>
                <label>Business Analyst</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <isActive>false</isActive>
                <label>CEO</label>
            </value>
            <value>
                <fullName>Designer</fullName>
                <isActive>false</isActive>
                <label>Designer</label>
            </value>
            <value>
                <fullName>Developer</fullName>
                <isActive>false</isActive>
                <label>Developer</label>
            </value>
            <value>
                <fullName>Manager</fullName>
                <isActive>false</isActive>
                <label>Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Social_Media__c</fullName>
    <label>Speaker Social Media</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Target__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Target__c</fullName>
    <label>Speaker Target</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admins</fullName>
            </value>
            <value>
                <fullName>Developers</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Marketing Technologists</fullName>
            </value>
            <value>
                <fullName>Executives</fullName>
            </value>
            <value>
                <fullName>End Users</fullName>
            </value>
            <value>
                <fullName>ISV/SI Partners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Title__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Title__c</fullName>
    <label>Speaker Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Type__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Type__c</fullName>
    <label>Speaker Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Speaker</fullName>
            </value>
            <value>
                <fullName>Co-Speaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Apex Classes/SessionSpeakerSelector.cls
/**
* @author: Muhammad Raza
* @description: This Class for  selecting session speakers
* @since: 01/01/24
* @Last Modified by:  Muhammad Raza
*/
public with sharing class SessionSpeakerSelector {
    
/**
* 
* @param whereClause - An optional WHERE clause to filter session speakers.
* @return List<Session_Speaker__c> - A list of session speakers that meet the specified criteria.
* @description: This method constructs a dynamic SOQL query to fetch session speakers with specified fields.
*                 WHERE clause is optional and can be used for additional filtering.
*/
    
    public  List<Session_Speaker__c> getSessionSpeakersList(String whereClause){
        String clause =  String.IsEmpty(whereClause)?'':'WHERE '+whereClause;
        String queryOnSessionSpeaker = 'SELECT Speaker__r.Id,Speaker__r.Approval_Status__c, Speaker__r.Speaker_Name__c, Speaker__r.Speaker_Title__c, Speaker__r.Email__c, Speaker__r.Phone_Number__c, Speaker__r.Speaker_Information__c, Speaker__r.Speaker_Profile_Image__c, Speaker__r.Speaker_Role__c, Speaker__r.Company_Name__c, Speaker__r.Speaker_Social_Media__c, Speaker__r.Speaker_Target__c, Speaker__r.Speaker_Type__c, Speaker__r.Speaker_Age__c , Speaker__r.Speaker_Gender__c , Session__c ' +
            'FROM Session_Speaker__c '
            + clause  ;
        List<Session_Speaker__c> sessionSpeakers = Database.query(queryOnSessionSpeaker);
        return   sessionSpeakers;
    }
    
/**
* 
* @param sessionId - The ID of the session to filter session speakers.
* @return List<Speaker__c> - A list of speakers associated with the specified session.
* @description: Retrieves a list of speakers associated with a specific session ID.
*/
    
    public  List<Speaker__c> getSpeakersBySessionId(String sessionId){
        String clause = 'Session__c  = \''+sessionId+'\' ';
        List<Session_Speaker__c> sessionSpeakers = getSessionSpeakersList(clause);
        
        List<Speaker__c> lstOfSpeakers = new List<Speaker__c>();
        
        for (Session_Speaker__c sessionSpeaker : sessionSpeakers) {
            Speaker__c speaker = sessionSpeaker.Speaker__r;
            if (speaker != null) {
                lstOfSpeakers.add(speaker);
            }
        }
        return lstOfSpeakers; 
    } 



    /**
     * @description gets session Session Speaker by speaker id (Speaker__c)
     * @param speakerId 
     * @return  `List<Session_Speaker__c>`
     */
    public  List<Session_Speaker__c> getSessionSpeakerBySpeakerId(String speakerId){
        String clause = 'Speaker__c  = \''+speakerId+'\' ';
        List<Session_Speaker__c> sessionSpeakers = getSessionSpeakersList(clause);
        
        if (sessionSpeakers.size() > 0) {
            return sessionSpeakers;
        }
        return sessionSpeakers; 
    } 


   

    public static List<Session__c> searchSessionsByTypedKeyword(String searchKey) {
        // Sanitize and format the search key
        String searchVal = '%' + String.escapeSingleQuotes(searchKey) + '%';
    
        // Query session speaker records based on the search key
        List<Session_Speaker__c> lstOfSessionSpeakers = [
            SELECT Session__r.Id 
            FROM Session_Speaker__c 
            WHERE (Session__r.Session_Title__c LIKE :searchVal) 
                OR ((Speaker__r.Speaker_Role__c LIKE :searchVal 
                OR Speaker__r.Speaker_Name__c LIKE :searchVal)
            AND Speaker__r.Approval_Status__c = 'Approved')
        ];
    
        // Extract session IDs from the result
        Set<Id> sessionIds = new Set<Id>();
        for (Session_Speaker__c ss : lstOfSessionSpeakers) {
            sessionIds.add(ss.Session__r.Id);
        }
    
        // Query and return the sessions using the extracted IDs
        List<Session__c> sessions = new List<Session__c>();
        if (!sessionIds.isEmpty()) {
            sessions = [SELECT Id, Session_Title__c, Session_Description__c
                        FROM Session__c
                        WHERE Id IN :sessionIds];
        }
        System.debug('Sessions'+sessions);
        return sessions;
    }
    

    /**
    * @description: Search sessions by speaker role
    * @param lstOfSearchKeys - List of roles to search for
    * @return List<Session__c> - List of sessions that match the specified roles
    */
    public static List<Session__c> searchSessionsByRole(List<String> lstOfRoles) {
        List<Id> sessionIds = new List<Id>();
        List<String> conditions = new List<String>();
        for (String searchKey : lstOfRoles) {
            String searchVal = '%' + String.escapeSingleQuotes(searchKey) + '%';
            conditions.add('Speaker__r.Speaker_Role__c LIKE \'' + searchVal + '\'');
        }
        String queryCondition = String.join(conditions, ' OR ');
        String finalQuery = 'SELECT Session__r.Id FROM Session_Speaker__c WHERE ' + queryCondition;
        List<Session_Speaker__c> sessionSpeakers = Database.query(finalQuery);

        for (Session_Speaker__c sessionSpeaker : sessionSpeakers) {
            sessionIds.add(sessionSpeaker.Session__r.Id);
        }

        List<Session__c> sessions = new List<Session__c>();
        if (!sessionIds.isEmpty()) {
            sessions = [SELECT Id, Session_Title__c, Session_Start_Time__c, Session_End_Time__c, Speaker_Name__c FROM Session__c WHERE Id IN :sessionIds];
        }
        System.debug('Sessions: ' + sessions);
        return sessions;
    }

}