force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session_Description__c.field-meta.xml
<CustomField>
    <fullName>Session_Description__c</fullName>
    <label>Session Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Duration__c.field-meta.xml
<CustomField>
    <fullName>Session_Duration__c</fullName>
    <description>This will show the total duration of session</description>
    <formula>TEXT(((Session_End_Time__c - Session_Start_Time__c)-MOD((Session_End_Time__c - Session_Start_Time__c),3600000))/3600000) &amp; &quot;h &quot; &amp;  TEXT(MOD((Session_End_Time__c - Session_Start_Time__c),3600000)/60000) &amp; &quot;m&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Time__c</fullName>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Time__c</fullName>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Session Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speaker_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speaker_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <description>Speaker Name</description>
    <formula>Speaker__r.Speaker_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Speaker Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <label>Speaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Profile_Image__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Profile_Image__c</fullName>
    <label>Speaker Profile Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Apex Classes/SessionController.cls
/**
* @author: Muhammad Raza
* @description:  Controller Class for handling session information.
* @since: 01/01/24
* @Last Modified by: Muhammad Raza
*/
public with sharing class SessionController {
    
/**
* 
* @description:  This method utilizes the SessionSelector and SessionSpeakerSelector 
*                classes to fetch session and speaker information for the specified event.
* @param eventId - The ID of the event for which to retrieve session information.
* @return List<DenormalizedSession> - A list of denormalized session information for the specified event.
*/
    @AuraEnabled(cacheable=true)
    public static List<DenormalizedSession> getSessions(String eventId){
        List<Session__c> sessionList = new SessionSelector().getSessionsByEventId(eventId);
        List<DenormalizedSession> denormalizedSessionList = new List<DenormalizedSession>();
        
        for (Session__c session : sessionList) {
            DenormalizedSession denormalizedSession = new DenormalizedSession();
            denormalizedSession.sessionTitle = session.Session_Title__c;
            denormalizedSession.sessionDescription = session.Session_Description__c;
            denormalizedSession.sessionStartDate = session.Session_Start_Date__c;
            denormalizedSession.sessionEndDate = session.Session_End_Date__c;
            denormalizedSession.sessionDuration = session.Session_Duration__c;
            if (session.Session_Start_Time__c != null) {
                DateTime sessionStartTime = DateTime.newInstance(session.Session_Start_Date__c, session.Session_Start_Time__c);
                denormalizedSession.sessionStartTime = sessionStartTime.format('hh:mm a');
            } else {
                denormalizedSession.sessionStartTime = 'N/A';
            }

            if (session.Session_End_Time__c != null) {
                DateTime sessionEndTime = DateTime.newInstance(session.Session_End_Date__c, session.Session_End_Time__c);
                denormalizedSession.sessionEndTime = sessionEndTime.format('hh:mm a');
            } else {
                denormalizedSession.sessionEndTime = 'N/A';
            }
            List<Speaker__c> lstOfSpeakers = new SessionSpeakerSelector().getSpeakersBySessionId(session.Id);
            List<DenormalizedSpeaker> denormalizedSpeakers = new List<DenormalizedSpeaker>();
            for (Speaker__c speaker : lstOfSpeakers) {
                DenormalizedSpeaker denormalizedSpeaker = new DenormalizedSpeaker();
                denormalizedSpeaker.speakerName = speaker.Speaker_Name__c;
                denormalizedSpeaker.speakerImage = speaker.Speaker_Profile_Image__c;
                denormalizedSpeakers.add(denormalizedSpeaker);
            }
            denormalizedSession.lstOfSpeakers = denormalizedSpeakers;
            
            denormalizedSessionList.add(denormalizedSession);
        }
        
        return denormalizedSessionList;
    }
    @AuraEnabled(cacheable=true)
    public static List<DenormalizedSession> getAllSessions() {
        // Fetching all sessions
        List<Session__c> lstOfSession = SessionSelector.searchAllSessions();
    
        //  all session Ids
        Set<Id> sessionIds = new Set<Id>();
        for (Session__c session : lstOfSession) {
            sessionIds.add(session.Id);
        }
    
       
        List<Session_Speaker__c> lstOfSessionSpeakers = [
            SELECT Session__r.Id, 
                   Speaker__r.Id, 
                   Speaker__r.Speaker_Profile_Image__c, 
                   Session__r.Session_Title__c, 
                   Speaker__r.Speaker_Name__c 
            FROM Session_Speaker__c  
            WHERE Session__r.Id IN :sessionIds 
              AND Speaker__r.approval_Status__c='Approved'
        ];
    
        
        Map<Id, List<Session_Speaker__c>> sessionSpeakersMap = new Map<Id, List<Session_Speaker__c>>();
        for (Session_Speaker__c sessionSpeaker : lstOfSessionSpeakers) {
            if (!sessionSpeakersMap.containsKey(sessionSpeaker.Session__r.Id)) {
                sessionSpeakersMap.put(sessionSpeaker.Session__r.Id, new List<Session_Speaker__c>());
            }
            sessionSpeakersMap.get(sessionSpeaker.Session__r.Id).add(sessionSpeaker);
        }
    
        
        List<DenormalizedSession> denormalizedSessionList = new List<DenormalizedSession>();
        for (Session__c session : lstOfSession) {
            if (sessionSpeakersMap.containsKey(session.Id)) {
                for (Session_Speaker__c sessionSpeaker : sessionSpeakersMap.get(session.Id)) {
                    DenormalizedSession denormalizedSession = new DenormalizedSession();
                    denormalizedSession.speakerImage = sessionSpeaker.Speaker__r.Speaker_Profile_Image__c;
                    denormalizedSession.sessionTitle = sessionSpeaker.Session__r.Session_Title__c;
                    denormalizedSession.speakerName = sessionSpeaker.Speaker__r.Speaker_Name__c;
                    System.debug('Denormalized Session::' + denormalizedSession);
                    denormalizedSessionList.add(denormalizedSession);
                }
            }
        }
        
        System.debug('denormalizedSessionList @@' + denormalizedSessionList);
        return denormalizedSessionList;
    }
    
   
    @AuraEnabled(cacheable=true)
   
    public static List<DenormalizedSession> getSessionsBySearch(String searchKey ){
        List<Session__c> lstOfSession= SessionSpeakerSelector.searchSessionsByTypedKeyword(searchKey);
  
        List<DenormalizedSession> denormalizedSessionList = new List<DenormalizedSession>();
        for (Session__c session : lstOfSession) {
            List<Session_Speaker__c> lstOfSessionSpeakers = [SELECT Session__r.Id, Speaker__r.Id, Speaker__r.Speaker_Profile_Image__c, Session__r.Session_Title__c, Speaker__r.Speaker_Name__c 
                                                             FROM Session_Speaker__c  
                                                             WHERE Session__r.Id = :session.Id AND Speaker__r.approval_Status__c='Approved'];
            
            for (Session_Speaker__c sessionSpeaker : lstOfSessionSpeakers) {
                DenormalizedSession denormalizedSession = new DenormalizedSession();
                denormalizedSession.speakerImage = sessionSpeaker.Speaker__r.Speaker_Profile_Image__c;
                denormalizedSession.sessionTitle = sessionSpeaker.Session__r.Session_Title__c;
                denormalizedSession.speakerName = sessionSpeaker.Speaker__r.Speaker_Name__c;
                denormalizedSessionList.add(denormalizedSession);
            }
        }
        System.debug('denormalizedSessionList @@'+denormalizedSessionList.size());
        System.debug('denormalizedSessionList @@'+denormalizedSessionList);
        return denormalizedSessionList;
      }
    

  


      @AuraEnabled(cacheable=true)
      public static List<DenormalizedSession> fetchOnlyFilteredSessions(List<String> levels, List<String> keywords, List<String> trackedProducts, List<String> speakerRole ){
        List<Session__c> lstOfSession= SessionSelector.filteredSessions(levels,keywords,trackedProducts,speakerRole);
        List<DenormalizedSession> denormalizedSessionList = new List<DenormalizedSession>();
        for (Session__c session : lstOfSession) {
            List<Session_Speaker__c> lstOfSessionSpeakers = [SELECT Session__r.Id, Speaker__r.Id, Speaker__r.Speaker_Profile_Image__c, Session__r.Session_Title__c, Speaker__r.Speaker_Name__c 
                                                             FROM Session_Speaker__c  
                                                             WHERE Session__r.Id = :session.Id AND Speaker__r.approval_Status__c='Approved'];
            
            for (Session_Speaker__c sessionSpeaker : lstOfSessionSpeakers) {
                DenormalizedSession denormalizedSession = new DenormalizedSession();
                denormalizedSession.speakerImage = sessionSpeaker.Speaker__r.Speaker_Profile_Image__c;
                denormalizedSession.sessionTitle = sessionSpeaker.Session__r.Session_Title__c;
                denormalizedSession.speakerName = sessionSpeaker.Speaker__r.Speaker_Name__c;
                denormalizedSessionList.add(denormalizedSession);
            }
        }
        System.debug('Denormalized'+denormalizedSessionList);
        System.debug('Denormalized List Size'+denormalizedSessionList.size());
        return denormalizedSessionList;
      }
      
    
}