force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session_Description__c.field-meta.xml
<CustomField>
    <fullName>Session_Description__c</fullName>
    <label>Session Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Time__c</fullName>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Time__c</fullName>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Title__c.field-meta.xml
<CustomField>
    <fullName>Session_Title__c</fullName>
    <label>Session Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Track__c.field-meta.xml
<CustomField>
    <fullName>Session_Track__c</fullName>
    <label>Session Track</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Data Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Analytics Cloud</fullName>
            </value>
            <value>
                <fullName>Integration Cloud</fullName>
            </value>
            <value>
                <fullName>Manufacturing Cloud</fullName>
            </value>
            <value>
                <fullName>Financial Services Cloud</fullName>
            </value>
            <value>
                <fullName>Education Services Cloud</fullName>
            </value>
            <value>
                <fullName>Nonprofit Cloud</fullName>
            </value>
            <value>
                <fullName>Health Cloud</fullName>
            </value>
            <value>
                <fullName>Vaccine Cloud</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Experience Cloud1</fullName>
                <isActive>false</isActive>
                <label>Experience Cloud1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Session Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speaker_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speaker_Object</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <description>Speaker Name</description>
    <formula>Speaker__r.Speaker_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Speaker Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Information__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Information__c</fullName>
    <label>Speaker Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Name__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Name__c</fullName>
    <label>Speaker Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Social_Media__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Social_Media__c</fullName>
    <label>Speaker Social Media</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Target__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Target__c</fullName>
    <label>Speaker Target</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admins</fullName>
            </value>
            <value>
                <fullName>Developers</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Marketing Technologists</fullName>
            </value>
            <value>
                <fullName>Executives</fullName>
            </value>
            <value>
                <fullName>End Users</fullName>
            </value>
            <value>
                <fullName>ISV/SI Partners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Speaker_Type__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Type__c</fullName>
    <label>Speaker Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Speaker</fullName>
            </value>
            <value>
                <fullName>Co-Speaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Apex Classes/ApprovalProcessControllerTest.cls
@isTest
public class ApprovalProcessControllerTest {
    

    @isTest
    static void testGetSessionTime() {
        // Test data setup
        String sessionStartTime = '12:00';
        String sessionEndTime =     '12:45';
        System.debug(sessionStartTime);
        System.debug(sessionEndTime);
        Time startTime = Time.newInstance(Integer.valueOf(sessionStartTime.split(':')[0]), Integer.valueOf(sessionStartTime.split(':')[1]), 0 ,0);
        Time endTime  = Time.newInstance(Integer.valueOf(sessionEndTime.split(':')[0]), Integer.valueOf(sessionEndTime.split(':')[1]), 0 ,0);
        Session__c testSession = new Session__c(
            // Name = 'Test Session',
            Session_Description__c = 'Test Description',
            Session_Track__c = 'Data Cloud',
            Session_Title__c = 'Test Title',
            Session_Start_Time__c = startTime,
            Session_End_Time__c = endTime
        );
        insert testSession;

        Speaker__c testSpeaker = new Speaker__c(
            Speaker_Name__c = 'Test Speaker',
            Speaker_Social_Media__c = 'Test Social Media',
            Phone_Number__c = '1234567890',
            Speaker_Target__c = 'Admins',
            Email__c = 'test@example.com',
            Company_Name__c = 'Test Company',
            Speaker_Information__c = 'Test Information',
            Speaker_Type__c = 'Primary Speaker',
           Approval_Status__c = 'Pending'
        );
        insert testSpeaker;
        
         Speaker__c testCoSpeaker = new Speaker__c(
            Speaker_Name__c = 'Test Co Speaker',
            Speaker_Social_Media__c = 'Test Social Media',
            Phone_Number__c = '1234567890',
            Speaker_Target__c = 'Admins',
            Email__c = 'testco@example.com',
            Company_Name__c = 'Test Company',
            Speaker_Information__c = 'Test Information',
            Speaker_Type__c = 'Co-Speaker',
           Approval_Status__c = 'Pending'
        );
        insert testCoSpeaker;

        Session_Speaker__c testSessionSpeaker = new Session_Speaker__c(
            Session__c = testSession.Id,
            Speaker__c = testSpeaker.Id
        );
        insert testSessionSpeaker;
        
        Session_Speaker__c testSessionCoSpeaker = new Session_Speaker__c(
            Session__c = testSession.Id,
            Speaker__c = testCoSpeaker.Id
        );
        insert testSessionCoSpeaker;





        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        Approval.ProcessSubmitRequest req1 = 
        new Approval.ProcessSubmitRequest();
    req1.setComments('Submitting request for approval.');
    req1.setObjectId(testSession.id);

    // Submit on behalf of a specific submitter
    req1.setSubmitterId(u.Id); 

    // Submit the record to specific process and skip the criteria evaluation
    req1.setProcessDefinitionNameOrId('Approve_Session');
    req1.setSkipEntryCriteria(true);

    // Submit the approval request for the account
    Approval.ProcessResult resultApprovl = Approval.process(req1);
       
       
       
    ProcessInstanceWorkitem testProcessInstanceWorkItem = [Select id, ProcessInstanceId ,OriginalActorId from ProcessInstanceWorkitem  limit 1];
       
       
       
       
       
       
       
       
        // ProcessInstance testProcessInstance = new ProcessInstance(
        //     // Populate required fields
        // );
        // insert testProcessInstance;

        // ProcessInstanceWorkitem testProcessInstanceWorkItem = new ProcessInstanceWorkitem(
        //     ProcessInstanceId = testProcessInstance.Id,
        //     // CurrentNodeId = 'Test Node',
        //     OriginalActorId = UserInfo.getUserId()
        //     // RemindersSent = 0
        //     // Populate other required fields
        // );
        // insert testProcessInstanceWorkItem;




































        // Call the method to test
        Test.startTest();
        List<DenormalizedSession> result = ApprovalProcessController.getSessionTime(testProcessInstanceWorkItem.Id);
        Test.stopTest();

        // Assert the result
        System.assertNotEquals(0, result.size(), 'Expected result list to contain at least one item');
        DenormalizedSession session = result[0];
        // System.assertEquals(testSession.Name, session.getSessionName(), 'Unexpected session name');
        // Add more assertions for other fields as needed
    }

    @isTest
    static void testSetSessionTime() {
        // Test data setup
        Session__c testSession = new Session__c(
            // Name = 'Test Session',
            Session_Description__c = 'Test Description',
            Session_Track__c = 'Data Cloud',
            Session_Title__c = 'Test Title',
            Session_Start_Time__c =Time.newInstance(12, 0, 0, 0),
            Session_End_Time__c = Time.newInstance(12, 45, 0, 0),
            Session_Start_Date__c = Date.newInstance(2024, 12, 9),
            Session_End_Date__c = Date.newInstance(2024, 12, 9)
        );
        insert testSession;
        Session__c testSessionInserted = [SELECT Name, Session_Start_Time__c, Session_End_Time__c FROM Session__c  limit 1];
        // Call the method to test
        system.debug(testSessionInserted.Name);
        Test.startTest();
        ApprovalProcessController.setSessionTime(testSessionInserted.Name, '09:00', '10:00');
        Test.stopTest();

        // Retrieve the session after the method execution
        Session__c updatedSession = [SELECT Session_Start_Time__c, Session_End_Time__c FROM Session__c WHERE Name = :testSessionInserted.Name];

        // Assert the result
        System.assertEquals(Time.newInstance(9, 0, 0, 0), updatedSession.Session_Start_Time__c, 'Unexpected start time');
        System.assertEquals(Time.newInstance(10, 0, 0, 0), updatedSession.Session_End_Time__c, 'Unexpected end time');
    }
    //
}